server:
  port: 7777

spring:
  application:
    name: system-service-auth
  redis:
    host: 127.0.0.1
    port: 6379
    password: 111111
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/je?useSSL=false
    username: cloud
    password: 111111
  freemarker:
    allow-request-override: false
    allow-session-override: false
    cache: true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    enabled: true
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    template-loader-path: classpath:/templates/
    
    
mybatis:
  type-aliases-package: org.je.cloud.**.entity
  mapper-locations: classpath*:org/je/cloud/**/mapper/*.xml
#  config-location: classpath:mybatis/mybatis-config.xml

#pagehelper物理分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  returnPageInfo: check
    
logging:
  config: classpath:logback.xml